# Week 8 Project

## Mira Ensley-Field

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
library(ggdendro)
```
<!-- put your content after this line -->

Each person from whom tissue was collected had sample, labeled by from which organ the sample came from
-maybe organ distinction isn't most important
-does probe do anything

```{r}
Narrow <- 
  NCI60 %>%
  gather(value=expression, key=cellLine, -Probe) %>%
  group_by(Probe, cellLine) %>%
  summarise(expression = mean(expression)) %>% 
  ungroup()
```

```{r}
keep <- 500


Best <-
  Narrow %>%
  group_by(Probe) %>%
  summarise(spread = sd(expression)) %>%
  arrange(desc(spread)) %>%
  mutate(i = row_number()) %>%
  head(keep)

Randomized <-
  Narrow %>%
  mutate(Probe = shuffle(Probe)) %>%
  group_by(Probe) %>%
  summarise(spread = sd(expression)) %>%
  arrange(desc(spread)) %>%
  mutate(i = row_number()) %>%
  head(keep)

Best %>% 
  ggplot(aes(x=i, y=spread)) + 
  geom_line() +
  geom_line(data=Randomized, color="red", size=1, alpha=.5)

Randomized %>% 
  ggplot(aes(x=i, y=spread)) + 
  geom_line() +
  geom_line(data=Randomized, color="green", size=1, alpha=.5)

```

```{r}
Keepers <-
  Narrow %>% 
  group_by(Probe) %>%
  filter(sd(expression) > 4.5)
```

```{r}
Keepers_Wide<-
  Keepers %>%
  spread(key=Probe, value=expression)

row.names(Keepers_Wide) <- Keepers_Wide$cellLine
```

#Clustering
```{r}
Dists<-dist(Keepers_Wide %>% select(-cellLine))
```

```{r}
Dendrogram2 <-hclust(Dists)
ddata2 <-dendro_data(Dendrogram2)
```

```{r}
ggdendro::ggdendrogram(Dendrogram2)
#ggdendrogram(Dendrogram, rotate = TRUE) +
  #geom_text(data = ddata$labels, aes(x=x, y=y, label = label), vjust = 0) 
```