# Week 4 Short Answer Questions

## Mira Ensley-Field

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->

```{r}
library(mosaicData)
library(ggplot2)

```

# Chapter 8

8.1

1. c.)

2.  a, b, g

3. e.) h.)

4. f.)

5. d.)

8.2

```{r}
ggplot(data=CPS85,aes(x=age,y=wage)) + geom_point(data=CPS85,aes(x=age,y=wage, shape=married)) + facet_wrap(~sector)

```
8.2

```{r}
ggplot(data=CPS85,aes(x=age,y=wage)) + geom_point(data=CPS85,aes(x=age,y=wage)) + facet_wrap(~married+sex, nrow=2,ncol=2) + facet_wrap(~sex)
```

8.3
A
```{r}
ggplot(data=CPS85,aes(x=age,y=wage)) + geom_point(data=CPS85,aes(x=age,y=wage)) 

```
B
```{r}
ggplot(data=CPS85,aes(x=age,y=wage)) + geom_point(data=CPS85,aes(x=age,y=wage,shape=sex)) 
```
C
```{r}
ggplot(data=CPS85,aes(x=age,y=wage)) + geom_point(data=CPS85,aes(x=age,y=wage)) + facet_wrap(~married,nrow=2,ncol=1)
```

D
```{r}
ggplot(data=CPS85,aes(x=age,y=wage)) + geom_point(data=CPS85,aes(x=age,y=wage,shape=married))
```


#Chapter 9

```{r}
library(mosaic)
library(mosaicData)
```

9.1
a.  quick presentation

b. data verb

c. comparison expression

d. summary function

e. data verb

f. summary function 

g. data verb

h. transformation

i. qquick presentation

9.3

```{r}
largest_color <-
  diamonds %>%
  group_by(color) %>%
  summarise(size=mean(carat)) %>%
  arrange(-size)
```

J colored diamonds are the largest average size (1.16)


```{r}
largest_table <-
  diamonds %>%
  group_by(clarity) %>%
  summarise(size=mean(carat),table_clarity=mean(table)) %>%
  mutate(table_per_carat=size/table_clarity) %>%
  arrange(-table_per_carat)
```

I1 have the largest table per carat